### ISSUE TITLE
Is there a place where one can chat about Amun?

### ISSUE THREAD

**Issue by Soupertonic** [AmrDeveloper/Amun#2]
I discovered this project [on Reddit](https://www.reddit.com/r/ProgrammingLanguages/comments/12t40pf/the_amun_programming_language/) and was wondering if there is a place where one can talk with other people about Amun? I was looking for a Discord link or something of that sort but didn't find anything.

**Comment by AmrDeveloper** [comment]
Hello @soupertonic, 

Welcome to this project, for now, there is a new subreddit and I will set up a discord server soon

https://www.reddit.com/r/Amun/

I will publish the link once it created

Thanks

**Comment by AmrDeveloper** [comment]
Discord server invite URL

https://discord.gg/NTsccntD

Welcome :D
